# this is the baseline project that a scenario will inherit settings from 
# leave empty for baseline projects
parent_baseline: 


data_sources:
# baseline data sources, not required for scenarios
  - blocks: blocks_2020.csv
  - households: synthetic_households.csv
  - jobs: jobs_2020.csv
  - housing_units: synthetic_housing_units.csv
  - persons: synthetic_persons.csv
  - transit_stops: transit_stops.csv
  - nodes: nodes.csv
  - edges: edges.csv
  - job_calib_targets: job_calib_targets.csv
  - household_calib_targets: household_calib_targets.csv
  - housing_unit_calib_targets: housing_unit_calib_targets.csv
  - travel_data: travel_data.csv
  - observed_data: observed_data.csv

# scenario data sources
  - block_capacity: block_capacity_0828_2026.csv
  - annual_household_control_totals: luvit_household_control_totals.csv
  - annual_job_control_totals: luvit_job_control_totals.csv

# optional: include zipped version of the data input tables
# data_loader will unzip it automatically if tables are missing
data_archive: mazsim_base_data.zip