data_sources:
# baseline data sources, not required for scenarios
  - blocks: blocks_2020_2026-10-07.csv
  - households: synthetic_households_2020_2026-10-07.csv
  - jobs: jobs_2020_2026-10-08.csv
  - housing_units: synthetic_housing_units_2020_2026-10-07.csv
  - persons: synthetic_persons_2020_2026-10-07.csv
  - transit_stops: transit_stops_2026-09-25.csv
  - urban_centers: urban_centers_2026-09-25.csv
  - nodes: nodes_2026-09-25.csv
  - edges: edges_2026-09-25.csv
#  - job_calib_targets: job_calib_targets.csv
  - travel_data: travel_data.csv
  - observed_data: observed_data_2026-10-08.csv

# history year data, used for calibration
  - history_year_blocks: blocks_2010_2026-10-06.csv
  - history_year_households: synthetic_households_2010_2026-10-06.csv
  - history_year_jobs: jobs_2010_2026-10-06.csv
  - history_year_housing_units: synthetic_housing_units_2010_2026-10-06.csv
  - history_year_persons: synthetic_persons_2010_2026-10-06.csv
  - household_calib_targets: household_calib_targets_2026-10-06.csv
  - housing_unit_calib_targets: housing_unit_calib_targets_2026-10-06.csv

# scenario data sources
  - block_capacity: block_capacity_2026-10-08.csv
  - annual_household_control_totals: luvit_household_control_totals.csv
  - annual_job_control_totals: luvit_job_control_totals.csv

# optional: include zipped version of the data input tables
# data_loader will unzip it automatically if tables are missing
data_archive: mazsim_base_data.zip