estimation_steps:
  - load_settings
  - load_data
  - build_networks
  - register_variables
  - estimate_hlcm
  - estimate_jlcm
  - estimate_hulcm
  - estimate_hupm


# chooser/out filter templates are filled with the model's filter_value and with base_year /
# historic_year from calibrate.yaml

hlcm:
  choosers: households
  chooser_filters_template: (recent_mover == 1) & (income_quartile == {value})
  chooser_sample_size: 2000
  alternatives: blocks
  choice_column: maz_id
  constrained_choices: true
  alt_sample_size: 100
  alt_capacity: vacant_housing_units
  out_alt_filters: vacant_housing_units > 0
  out_chooser_filters_template: (maz_id == -1) & (income_quartile == {value})
  # addl_expl_vars:
  models: # order seems backwards but this will mean high income is placed first
    - name: hlcm1  # high income
      filter_value: 4
    - name: hlcm2  # mid-high income
      filter_value: 3
    - name: hlcm3  # mid-low income
      filter_value: 2
    - name: hlcm4  # low income
      filter_value: 1

jlcm:
  choosers: jobs
  chooser_filters_template: aggr_sector_id == {value}
  chooser_sample_size: 2000
  alternatives: blocks
  choice_column: maz_id
  constrained_choices: true
  alt_sample_size: 100
  alt_capacity: vacant_job_spaces
  out_alt_filters: vacant_job_spaces > 0
  out_chooser_filters_template: (maz_id == -1) & (aggr_sector_id == {value})
  # addl_expl_vars: 
  models:
    - name: jlcm1  # Agriculture, Mining, Utilities & Construction
      filter_value: 1
    - name: jlcm2  # Manufacturing, Wholesale Trade, Transportation & Warehousing
      filter_value: 2
    - name: jlcm3  # Retail Trade, Arts/Entertainment/Recreation, Accommodation & Food Services
      filter_value: 3
    - name: jlcm4  # Information, Finance, Real Estate, Professional/Management/Admin Services
      filter_value: 4
    - name: jlcm5  # Educational Services, Health Care, Government
      filter_value: 5

hulcm:
  choosers: housing_units
  chooser_filters_template: (year_built > {historic_year}) & (unit_type_id == {value})
  chooser_sample_size: 2000
  alternatives: blocks
  choice_column: maz_id
  constrained_choices: true
  alt_sample_size: 50
  alt_capacity: vacant_hu_spaces
  out_alt_filters: vacant_hu_spaces > 0
  out_chooser_filters_template: (maz_id == -1) & (year_built > {historic_year}) & (unit_type_id == {value})
  # addl_expl_vars:
  models:
    - name: hulcm1  # single-family
      filter_value: 1
    - name: hulcm2  # middle-density
      filter_value: 2
    - name: hulcm3  # multi-family
      filter_value: 3

hupm:
  tables:
    - blocks
  out_filters: all_blocks == 1
  # addl_expl_vars:
  models:
    - name: hupm_value  # residential value
      left_side: res_value
      filters: (res_value > 0) & (value_impute == False)
    - name: hupm_rent  # residential rent
      left_side: res_rent
      filters: (res_rent > 0) & (rent_impute == False)

global_expl_vars:
# travel skim variables
  - st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
  - st_ln_zones_total_households_15_minutes_am_single_vehicle_to_work_travel_time
  - st_ln_zones_total_jobs_30_minutes_am_single_vehicle_to_work_travel_time
  - st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time

    # hh accessibility variables
  - st_is_transit_stop_sum_800_flat
  - st_is_transit_stop_sum_1600_flat
  - st_is_transit_stop_sum_3200_flat
  - st_is_urban_center_sum_800_flat
  - st_is_urban_center_sum_1600_flat
  - st_is_urban_center_sum_3200_flat
  - st_sum_income_ave_800_flat 
  - st_sum_income_ave_1600_flat 
  - st_sum_income_ave_3200_flat 
  - st_ln_res_value_ave_800_flat
  - st_ln_res_value_ave_1600_flat
  - st_ln_res_value_ave_3200_flat
  - st_ln_res_rent_ave_800_flat
  - st_ln_res_rent_ave_1600_flat
  - st_ln_res_rent_ave_3200_flat
  - st_prop_aggr_sector_id_1_ave_800_flat
  - st_prop_aggr_sector_id_1_ave_1600_flat
  - st_prop_aggr_sector_id_1_ave_3200_flat
  - st_prop_aggr_sector_id_2_ave_800_flat
  - st_prop_aggr_sector_id_2_ave_1600_flat
  - st_prop_aggr_sector_id_2_ave_3200_flat
  - st_prop_aggr_sector_id_3_ave_800_flat
  - st_prop_aggr_sector_id_3_ave_1600_flat
  - st_prop_aggr_sector_id_3_ave_3200_flat
  - st_prop_aggr_sector_id_4_ave_800_flat
  - st_prop_aggr_sector_id_4_ave_1600_flat
  - st_prop_aggr_sector_id_4_ave_3200_flat
  - st_prop_aggr_sector_id_5_ave_800_flat
  - st_prop_aggr_sector_id_5_ave_1600_flat
  - st_prop_aggr_sector_id_5_ave_3200_flat
  - st_prop_tenure_1_ave_800_flat
  - st_prop_tenure_1_ave_1600_flat
  - st_prop_tenure_1_ave_3200_flat

    # housing unit variables
  - st_sum_sf_ave_800_flat
  - st_sum_sf_ave_1600_flat
  - st_sum_sf_ave_3200_flat
  - st_sum_middle_ave_800_flat
  - st_sum_middle_ave_1600_flat
  - st_sum_middle_ave_3200_flat
  - st_sum_mf_ave_800_flat
  - st_sum_mf_ave_1600_flat
  - st_sum_mf_ave_3200_flat
  - st_sum_sf_built_prev_10_years_ave_800_flat
  - st_sum_sf_built_prev_10_years_ave_1600_flat
  - st_sum_sf_built_prev_10_years_ave_3200_flat
  - st_sum_middle_built_prev_10_years_ave_800_flat
  - st_sum_middle_built_prev_10_years_ave_1600_flat
  - st_sum_middle_built_prev_10_years_ave_3200_flat
  - st_sum_mf_built_prev_10_years_ave_800_flat
  - st_sum_mf_built_prev_10_years_ave_1600_flat
  - st_sum_mf_built_prev_10_years_ave_3200_flat
  - st_mean_year_built

    # block group variables
  - st_block_groups_median_year_built
  - st_block_groups_median_income
  - st_block_groups_prop_children_0
  - st_ln_block_groups_density_housing_units
  - st_ln_block_groups_density_jobs
  - st_block_groups_prop_cars_0
  - st_block_groups_prop_worker_aggr_sector_1
  - st_block_groups_prop_worker_aggr_sector_2
  - st_block_groups_prop_worker_aggr_sector_3
  - st_block_groups_prop_worker_aggr_sector_4
  - st_block_groups_prop_worker_aggr_sector_5
  - st_block_groups_prop_worker_aggr_occ_1
  - st_block_groups_prop_worker_aggr_occ_2
  - st_block_groups_prop_worker_aggr_occ_3
  - st_block_groups_prop_worker_aggr_occ_4
  - st_block_groups_prop_worker_aggr_occ_5
  - st_block_groups_prop_worker_aggr_occ_6