# tables and variables to be saved to output/output_summaries
# in the output_summary step.

geography: 
  - counties

variables:
  - sum_persons
  - total_households
  - total_housing_units
  - total_jobs
  - housing_unit_capacity
  - job_capacity

# variables for which the simulation end year subtracted from the first year 
# (not the base year if observed data is provided) should be calculated.
diff_variables:
  - total_households
  - total_housing_units
  - total_jobs
