# orca steps to run during simulation:
preprocessing_steps:
  - load_settings
  - start_run_log
  - delete_non_archived_run_files
  - initialize_submodels
  - load_data
  - build_networks
  - register_variables
  - subregional_ct
  - setup_lcms

simulation_steps:
  - job_control_totals
  - household_control_totals
  - housing_unit_control_totals
  - place_observed_data
  - housing_unit_lcms
  - rent_price_model
  - value_price_model
  - clip_price_data
  - job_lcms
  - household_lcms
  - save_full_tables
  - save_output_summaries

postprocessing_steps:
  - save_diff_summaries
  - archive_results

random_seed: 42