modelmanager_version: '0.3'

saved_object:
    alt_capacity: vacant_housing_units
    alt_filters: null
    alt_sample_size: 100
    alternatives: blocks
    choice_column: maz_id
    chooser_filters: (recent_mover == 1) & (income_quartile == 4)
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 4.584746419077183
    - 0.14883309909848813
    - 0.37610333379242444
    - 0.23100511261107975
    - 0.20317416094518592
    - -0.9062257841541287
    - -0.1655800039359015
    max_iter: null
    mct_intx_ops: null
    model_expression: st_sum_income_ave_800_flat + st_block_groups_prop_worker_aggr_occ_2
        + st_mean_year_built + st_ln_block_groups_density_housing_units + st_ln_res_value_ave_800_flat
        + st_sum_income_ave_3200_flat + st_block_groups_median_year_built - 1
    name: hlcm1
    out_alt_filters: vacant_housing_units > 0
    out_alternatives: null
    out_chooser_filters: (maz_id == -1) & (income_quartile == 4)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         113,010\nModel:\
        \         Multinomial Logit   Df Residuals:             113,003\nMethod: \
        \      Maximum Likelihood   Df Model:                       7\nDate:     \
        \            2026-09-29   Pseudo R-squ.:              0.174\nTime:       \
        \               21:08   Pseudo R-bar-squ.:          0.174\nAIC:          \
        \       860,088.506   Log-Likelihood:      -430,037.253\nBIC:            \
        \     860,155.953   LL-Null:             -520,430.283\n=============================================================================================\n\
        \                                              coef   std err         z  \
        \   P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------\n\
        st_sum_income_ave_800_flat                  4.5847     0.014   339.263   \
        \  0.000             \nst_block_groups_prop_worker_aggr_occ_2      0.1488\
        \     0.004    36.445     0.000             \nst_mean_year_built         \
        \                 0.3761     0.008    48.307     0.000             \nst_ln_block_groups_density_housing_units\
        \    0.2310     0.004    62.146     0.000             \nst_ln_res_value_ave_800_flat\
        \                0.2032     0.005    38.691     0.000             \nst_sum_income_ave_3200_flat\
        \                -0.9062     0.020   -44.649     0.000             \nst_block_groups_median_year_built\
        \          -0.1656     0.008   -22.038     0.000             \n============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: '0.3'
