modelmanager_version: '0.3'

saved_object:
    alt_capacity: vacant_housing_units
    alt_filters: null
    alt_sample_size: 100
    alternatives: blocks
    choice_column: maz_id
    chooser_filters: (recent_mover == 1) & (income_quartile == 2)
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 0.17274431447012076
    - 0.10276795672605635
    - 0.4261186272551598
    - 4.032850509260826
    - -0.6822712236188241
    - 0.3591525707009218
    - -0.2446872125209814
    - -0.9673770984668797
    - -0.031723974570560635
    - -0.0915941193029972
    - -0.19648242597178286
    - -0.2082800390344702
    max_iter: null
    mct_intx_ops: null
    model_expression: st_sum_mf_ave_800_flat + st_sum_middle_ave_800_flat + st_mean_year_built
        + st_sum_income_ave_800_flat + st_block_groups_median_income + st_ln_block_groups_density_housing_units
        + st_block_groups_prop_cars_0 + st_sum_income_ave_1600_flat + st_sum_sf_built_prev_10_years_ave_800_flat
        + st_is_transit_stop_sum_3200_flat + st_prop_tenure_1_ave_800_flat + st_block_groups_median_year_built
        - 1
    name: hlcm3
    out_alt_filters: vacant_housing_units > 0
    out_alternatives: null
    out_chooser_filters: (maz_id == -1) & (income_quartile == 2)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         134,242\nModel:\
        \         Multinomial Logit   Df Residuals:             134,230\nMethod: \
        \      Maximum Likelihood   Df Model:                      12\nDate:     \
        \            2026-09-29   Pseudo R-squ.:              0.179\nTime:       \
        \               21:17   Pseudo R-bar-squ.:          0.179\nAIC:          \
        \     1,014,755.290   Log-Likelihood:      -507,365.645\nBIC:            \
        \   1,014,872.979   LL-Null:             -618,207.256\n================================================================================================\n\
        \                                                coef   std err          z\
        \     P>|z|   Conf. Int.\n------------------------------------------------------------------------------------------------\n\
        st_sum_mf_ave_800_flat                        0.1727     0.005     37.898\
        \     0.000             \nst_sum_middle_ave_800_flat                    0.1028\
        \     0.004     25.407     0.000             \nst_mean_year_built        \
        \                    0.4261     0.007     57.758     0.000             \n\
        st_sum_income_ave_800_flat                    4.0329     0.022    181.972\
        \     0.000             \nst_block_groups_median_income                -0.6823\
        \     0.004   -154.402     0.000             \nst_ln_block_groups_density_housing_units\
        \      0.3592     0.004     84.238     0.000             \nst_block_groups_prop_cars_0\
        \                  -0.2447     0.004    -65.362     0.000             \nst_sum_income_ave_1600_flat\
        \                  -0.9674     0.023    -41.317     0.000             \nst_sum_sf_built_prev_10_years_ave_800_flat\
        \   -0.0317     0.003     -9.128     0.000             \nst_is_transit_stop_sum_3200_flat\
        \             -0.0916     0.003    -26.934     0.000             \nst_prop_tenure_1_ave_800_flat\
        \                -0.1965     0.005    -42.590     0.000             \nst_block_groups_median_year_built\
        \            -0.2083     0.007    -29.534     0.000             \n================================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: '0.3'
