modelmanager_version: '0.3'

saved_object:
    alt_capacity: vacant_hu_spaces
    alt_filters: null
    alt_sample_size: 50
    alternatives: blocks
    choice_column: maz_id
    chooser_filters: (year_built > 2010) & (unit_type_id == 1)
    chooser_sample_size: null
    chooser_size: null
    choosers: housing_units
    constrained_choices: true
    fitted_parameters:
    - 0.7760102699946747
    - 0.22588560486458603
    - -0.4223277512689404
    - 0.9304672510725258
    - 0.5122518431931924
    - -0.3926263748945707
    - -0.2134495766952876
    - -0.1405910722664064
    max_iter: null
    mct_intx_ops: null
    model_expression: st_sum_sf_built_prev_10_years_ave_800_flat + st_block_groups_prop_worker_aggr_sector_1
        + st_block_groups_prop_cars_0 + st_sum_income_ave_800_flat + st_mean_year_built
        + st_block_groups_median_year_built + st_sum_middle_ave_3200_flat + st_ln_res_rent_ave_800_flat
        - 1
    name: hulcm1
    out_alt_filters: vacant_hu_spaces > 0
    out_alternatives: null
    out_chooser_filters: (maz_id == -1) & (year_built > 2010) & (unit_type_id == 1)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         16,188\nModel:\
        \         Multinomial Logit   Df Residuals:             16,180\nMethod:  \
        \     Maximum Likelihood   Df Model:                      8\nDate:       \
        \          2026-09-29   Pseudo R-squ.:             0.265\nTime:          \
        \            21:57   Pseudo R-bar-squ.:         0.265\nAIC:              \
        \    93,064.080   Log-Likelihood:      -46,524.040\nBIC:                 \
        \ 93,125.616   LL-Null:             -63,327.828\n===============================================================================================\n\
        \                                                coef   std err         z\
        \     P>|z|   Conf. Int.\n-----------------------------------------------------------------------------------------------\n\
        st_sum_sf_built_prev_10_years_ave_800_flat    0.7760     0.011    68.051 \
        \    0.000             \nst_block_groups_prop_worker_aggr_sector_1     0.2259\
        \     0.011    21.112     0.000             \nst_block_groups_prop_cars_0\
        \                  -0.4223     0.018   -23.767     0.000             \nst_sum_income_ave_800_flat\
        \                    0.9305     0.036    25.561     0.000             \nst_mean_year_built\
        \                            0.5123     0.021    24.231     0.000        \
        \     \nst_block_groups_median_year_built            -0.3926     0.024   -16.504\
        \     0.000             \nst_sum_middle_ave_3200_flat                  -0.2134\
        \     0.010   -21.889     0.000             \nst_ln_res_rent_ave_800_flat\
        \                  -0.1406     0.009   -15.022     0.000             \n==============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: '0.3'
