modelmanager_version: '0.3'

saved_object:
    alt_capacity: vacant_hu_spaces
    alt_filters: null
    alt_sample_size: 50
    alternatives: blocks
    choice_column: maz_id
    chooser_filters: (year_built > 2010) & (unit_type_id == 2)
    chooser_sample_size: null
    chooser_size: null
    choosers: housing_units
    constrained_choices: true
    fitted_parameters:
    - 0.7317551134722943
    - 0.7354793455801263
    - 0.23965250608610628
    - -0.16007048529793944
    - 0.2543372421212519
    - 0.13790936619909616
    - -0.15110997348137684
    - 0.36993071350029466
    - -0.28664618976707323
    - -0.33319662896760954
    - 0.23543117380172296
    - -0.19660169054827414
    max_iter: null
    mct_intx_ops: null
    model_expression: st_sum_middle_built_prev_10_years_ave_800_flat + st_sum_income_ave_800_flat
        + st_block_groups_prop_worker_aggr_sector_5 + st_is_urban_center_sum_3200_flat
        + st_sum_middle_ave_3200_flat + st_block_groups_prop_worker_aggr_occ_3 + st_block_groups_prop_worker_aggr_occ_6
        + st_mean_year_built + st_block_groups_median_year_built + st_block_groups_median_income
        + st_ln_res_value_ave_800_flat + st_sum_mf_ave_800_flat - 1
    name: hulcm2
    out_alt_filters: vacant_hu_spaces > 0
    out_alternatives: null
    out_chooser_filters: (maz_id == -1) & (year_built > 2010) & (unit_type_id == 2)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          4,250\nModel:\
        \         Multinomial Logit   Df Residuals:              4,238\nMethod:  \
        \     Maximum Likelihood   Df Model:                     12\nDate:       \
        \          2026-09-29   Pseudo R-squ.:             0.224\nTime:          \
        \            22:00   Pseudo R-bar-squ.:         0.223\nAIC:              \
        \    25,835.763   Log-Likelihood:      -12,905.882\nBIC:                 \
        \ 25,912.019   LL-Null:             -16,626.098\n===================================================================================================\n\
        \                                                    coef   std err      \
        \   z     P>|z|   Conf. Int.\n---------------------------------------------------------------------------------------------------\n\
        st_sum_middle_built_prev_10_years_ave_800_flat    0.7318     0.015    48.314\
        \     0.000             \nst_sum_income_ave_800_flat                     \
        \   0.7355     0.070    10.548     0.000             \nst_block_groups_prop_worker_aggr_sector_5\
        \         0.2397     0.019    12.580     0.000             \nst_is_urban_center_sum_3200_flat\
        \                 -0.1601     0.018    -8.706     0.000             \nst_sum_middle_ave_3200_flat\
        \                       0.2543     0.024    10.430     0.000             \n\
        st_block_groups_prop_worker_aggr_occ_3            0.1379     0.024     5.714\
        \     0.000             \nst_block_groups_prop_worker_aggr_occ_6         \
        \  -0.1511     0.026    -5.916     0.000             \nst_mean_year_built\
        \                                0.3699     0.035    10.698     0.000    \
        \         \nst_block_groups_median_year_built                -0.2866     0.032\
        \    -8.991     0.000             \nst_block_groups_median_income        \
        \            -0.3332     0.030   -11.129     0.000             \nst_ln_res_value_ave_800_flat\
        \                      0.2354     0.026     9.027     0.000             \n\
        st_sum_mf_ave_800_flat                           -0.1966     0.021    -9.543\
        \     0.000             \n==================================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: '0.3'
