modelmanager_version: '0.3'

saved_object:
    filters: (res_rent > 0) & (rent_impute == False)
    fitted_parameters:
    - 1865.7889159362378
    - 608.4588186338823
    - 132.2623188547451
    - -27.10978166900115
    - -90.62103093793529
    - -18.167329126134966
    - -18.739491011704075
    - -15.158838282561689
    - -36.21981935377772
    - 14.122597589144014
    - -20.68904314914792
    - -21.475560626708386
    - 17.267353090302713
    model:
        fit_filters: (res_rent > 0) & (rent_impute == False)
        fit_parameters:
            Coefficient:
                Intercept: 1865.7889159362378
                st_block_groups_median_income: 132.2623188547451
                st_block_groups_prop_worker_aggr_occ_1: -36.21981935377772
                st_block_groups_prop_worker_aggr_sector_1: -15.158838282561689
                st_block_groups_prop_worker_aggr_sector_5: -18.167329126134966
                st_ln_block_groups_density_jobs: 14.122597589144014
                st_ln_res_rent_ave_1600_flat: -90.62103093793529
                st_ln_res_rent_ave_800_flat: 608.4588186338823
                st_ln_res_value_ave_1600_flat: -27.10978166900115
                st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time: -20.68904314914792
                st_mean_year_built: 17.267353090302713
                st_sum_middle_ave_3200_flat: -18.739491011704075
                st_sum_sf_built_prev_10_years_ave_3200_flat: -21.475560626708386
            Std. Error:
                Intercept: 2.46745662734126
                st_block_groups_median_income: 4.223028870154645
                st_block_groups_prop_worker_aggr_occ_1: 4.5128437280482405
                st_block_groups_prop_worker_aggr_sector_1: 2.9503114924600427
                st_block_groups_prop_worker_aggr_sector_5: 2.6769162348986923
                st_ln_block_groups_density_jobs: 2.9010259229452346
                st_ln_res_rent_ave_1600_flat: 8.401587602065918
                st_ln_res_rent_ave_800_flat: 7.725414842537547
                st_ln_res_value_ave_1600_flat: 4.365658222132875
                st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time: 4.085340444465421
                st_mean_year_built: 2.7314464173858544
                st_sum_middle_ave_3200_flat: 3.246025508739641
                st_sum_sf_built_prev_10_years_ave_3200_flat: 3.1687902408710507
            T-Score:
                Intercept: 756.1587487544481
                st_block_groups_median_income: 31.319302548339373
                st_block_groups_prop_worker_aggr_occ_1: -8.02594140999481
                st_block_groups_prop_worker_aggr_sector_1: -5.138046718559156
                st_block_groups_prop_worker_aggr_sector_5: -6.786663284151103
                st_ln_block_groups_density_jobs: 4.86813905296172
                st_ln_res_rent_ave_1600_flat: -10.78617937824655
                st_ln_res_rent_ave_800_flat: 78.76066606593044
                st_ln_res_value_ave_1600_flat: -6.209781043225245
                st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time: -5.064215193418266
                st_mean_year_built: 6.3216883847308
                st_sum_middle_ave_3200_flat: -5.77305722374936
                st_sum_sf_built_prev_10_years_ave_3200_flat: -6.777211173436678
        fit_rsquared: 0.7165556840679725
        fit_rsquared_adj: 0.7164033424282008
        fitted: true
        model_expression: res_rent ~ st_ln_res_rent_ave_800_flat + st_block_groups_median_income
            + st_ln_res_value_ave_1600_flat + st_ln_res_rent_ave_1600_flat + st_block_groups_prop_worker_aggr_sector_5
            + st_sum_middle_ave_3200_flat + st_block_groups_prop_worker_aggr_sector_1
            + st_block_groups_prop_worker_aggr_occ_1 + st_ln_block_groups_density_jobs
            + st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time
            + st_sum_sf_built_prev_10_years_ave_3200_flat + st_mean_year_built + 1
        model_type: regression
        name: RegressionModel
        predict_filters: all_blocks == 1
        ytransform: null
    model_expression: res_rent ~ st_ln_res_rent_ave_800_flat + st_block_groups_median_income
        + st_ln_res_value_ave_1600_flat + st_ln_res_rent_ave_1600_flat + st_block_groups_prop_worker_aggr_sector_5
        + st_sum_middle_ave_3200_flat + st_block_groups_prop_worker_aggr_sector_1
        + st_block_groups_prop_worker_aggr_occ_1 + st_ln_block_groups_density_jobs
        + st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time
        + st_sum_sf_built_prev_10_years_ave_3200_flat + st_mean_year_built + 1
    name: hupm_rent
    out_column: res_rent
    out_filters: all_blocks == 1
    out_tables: null
    out_transform: null
    summary_table: "                            OLS Regression Results           \
        \                 \n==============================================================================\n\
        Dep. Variable:               res_rent   R-squared:                       0.717\n\
        Model:                            OLS   Adj. R-squared:                  0.716\n\
        Method:                 Least Squares   F-statistic:                     4704.\n\
        Date:                Tue, 29 Sep 2026   Prob (F-statistic):              \
        \ 0.00\nTime:                        22:04:24   Log-Likelihood:          \
        \  -1.6208e+05\nNo. Observations:               22340   AIC:             \
        \            3.242e+05\nDf Residuals:                   22327   BIC:     \
        \                    3.243e+05\nDf Model:                          12    \
        \                                     \nCovariance Type:            nonrobust\
        \                                         \n=================================================================================================================================================\n\
        \                                                                        \
        \            coef    std err          t      P>|t|      [0.025      0.975]\n\
        -------------------------------------------------------------------------------------------------------------------------------------------------\n\
        Intercept                                                                \
        \      1865.7889      2.467    756.159      0.000    1860.953    1870.625\n\
        st_ln_res_rent_ave_800_flat                                              \
        \       608.4588      7.725     78.761      0.000     593.316     623.601\n\
        st_block_groups_median_income                                            \
        \       132.2623      4.223     31.319      0.000     123.985     140.540\n\
        st_ln_res_value_ave_1600_flat                                            \
        \       -27.1098      4.366     -6.210      0.000     -35.667     -18.553\n\
        st_ln_res_rent_ave_1600_flat                                             \
        \       -90.6210      8.402    -10.786      0.000    -107.089     -74.153\n\
        st_block_groups_prop_worker_aggr_sector_5                                \
        \       -18.1673      2.677     -6.787      0.000     -23.414     -12.920\n\
        st_sum_middle_ave_3200_flat                                              \
        \       -18.7395      3.246     -5.773      0.000     -25.102     -12.377\n\
        st_block_groups_prop_worker_aggr_sector_1                                \
        \       -15.1588      2.950     -5.138      0.000     -20.942      -9.376\n\
        st_block_groups_prop_worker_aggr_occ_1                                   \
        \       -36.2198      4.513     -8.026      0.000     -45.065     -27.374\n\
        st_ln_block_groups_density_jobs                                          \
        \        14.1226      2.901      4.868      0.000       8.436      19.809\n\
        st_ln_zones_total_households_30_minutes_am_single_vehicle_to_work_travel_time\
        \   -20.6890      4.085     -5.064      0.000     -28.697     -12.681\nst_sum_sf_built_prev_10_years_ave_3200_flat\
        \                                     -21.4756      3.169     -6.777     \
        \ 0.000     -27.687     -15.265\nst_mean_year_built                      \
        \                                         17.2674      2.731      6.322  \
        \    0.000      11.914      22.621\n==============================================================================\n\
        Omnibus:                     8964.886   Durbin-Watson:                   1.519\n\
        Prob(Omnibus):                  0.000   Jarque-Bera (JB):           242248.511\n\
        Skew:                           1.348   Prob(JB):                        \
        \ 0.00\nKurtosis:                      18.905   Cond. No.                \
        \         9.38\n==============================================================================\n\
        \nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors\
        \ is correctly specified."
    tables: blocks
    tags: []
    template: OLSRegressionStep
    template_version: '0.3'
