modelmanager_version: '0.3'

saved_object:
    filters: (res_value > 0) & (value_impute == False)
    fitted_parameters:
    - 803609.0217720446
    - 319539.9822073289
    - 65145.38617460171
    - -15232.670498999052
    - -21705.446257195228
    - -20297.157058442386
    - 21350.617895256655
    - -30690.946997266627
    - -35357.98471423161
    - 19120.86326798441
    - -10785.450391964881
    - 8703.706417206195
    - -14785.150885436538
    model:
        fit_filters: (res_value > 0) & (value_impute == False)
        fit_parameters:
            Coefficient:
                Intercept: 803609.0217720446
                st_block_groups_median_income: 65145.38617460171
                st_block_groups_median_year_built: -15232.670498999052
                st_block_groups_prop_worker_aggr_occ_2: -14785.150885436538
                st_block_groups_prop_worker_aggr_sector_2: -21705.446257195228
                st_block_groups_prop_worker_aggr_sector_3: -10785.450391964881
                st_block_groups_prop_worker_aggr_sector_5: -20297.157058442386
                st_is_urban_center_sum_3200_flat: 8703.706417206195
                st_ln_res_value_ave_3200_flat: -35357.98471423161
                st_ln_res_value_ave_800_flat: 319539.9822073289
                st_prop_aggr_sector_id_4_ave_3200_flat: 19120.86326798441
                st_sum_middle_ave_3200_flat: 21350.617895256655
                st_sum_sf_ave_3200_flat: -30690.946997266627
            Std. Error:
                Intercept: 1088.3048853948014
                st_block_groups_median_income: 1551.8988010479309
                st_block_groups_median_year_built: 1078.0405946088954
                st_block_groups_prop_worker_aggr_occ_2: 2330.351431039641
                st_block_groups_prop_worker_aggr_sector_2: 1163.191705025495
                st_block_groups_prop_worker_aggr_sector_3: 1481.1146080096619
                st_block_groups_prop_worker_aggr_sector_5: 1342.0823456880792
                st_is_urban_center_sum_3200_flat: 1180.5179114072844
                st_ln_res_value_ave_3200_flat: 3302.9693759037605
                st_ln_res_value_ave_800_flat: 2943.819199391903
                st_prop_aggr_sector_id_4_ave_3200_flat: 2036.3169631692688
                st_sum_middle_ave_3200_flat: 1470.438828381222
                st_sum_sf_ave_3200_flat: 1915.8734101894265
            T-Score:
                Intercept: 738.4043134939355
                st_block_groups_median_income: 41.97785714546065
                st_block_groups_median_year_built: -14.129960017438252
                st_block_groups_prop_worker_aggr_occ_2: -6.344601371493755
                st_block_groups_prop_worker_aggr_sector_2: -18.660248489924957
                st_block_groups_prop_worker_aggr_sector_3: -7.281982321718161
                st_block_groups_prop_worker_aggr_sector_5: -15.123630173404994
                st_is_urban_center_sum_3200_flat: 7.37278641272845
                st_ln_res_value_ave_3200_flat: -10.704908429421007
                st_ln_res_value_ave_800_flat: 108.54606229667074
                st_prop_aggr_sector_id_4_ave_3200_flat: 9.389924856406054
                st_sum_middle_ave_3200_flat: 14.519895342236808
                st_sum_sf_ave_3200_flat: -16.01929795258871
        fit_rsquared: 0.7762065410106667
        fit_rsquared_adj: 0.7761302911098185
        fitted: true
        model_expression: res_value ~ st_ln_res_value_ave_800_flat + st_block_groups_median_income
            + st_block_groups_median_year_built + st_block_groups_prop_worker_aggr_sector_2
            + st_block_groups_prop_worker_aggr_sector_5 + st_sum_middle_ave_3200_flat
            + st_sum_sf_ave_3200_flat + st_ln_res_value_ave_3200_flat + st_prop_aggr_sector_id_4_ave_3200_flat
            + st_block_groups_prop_worker_aggr_sector_3 + st_is_urban_center_sum_3200_flat
            + st_block_groups_prop_worker_aggr_occ_2 + 1
        model_type: regression
        name: RegressionModel
        predict_filters: all_blocks == 1
        ytransform: null
    model_expression: res_value ~ st_ln_res_value_ave_800_flat + st_block_groups_median_income
        + st_block_groups_median_year_built + st_block_groups_prop_worker_aggr_sector_2
        + st_block_groups_prop_worker_aggr_sector_5 + st_sum_middle_ave_3200_flat
        + st_sum_sf_ave_3200_flat + st_ln_res_value_ave_3200_flat + st_prop_aggr_sector_id_4_ave_3200_flat
        + st_block_groups_prop_worker_aggr_sector_3 + st_is_urban_center_sum_3200_flat
        + st_block_groups_prop_worker_aggr_occ_2 + 1
    name: hupm_value
    out_column: res_value
    out_filters: all_blocks == 1
    out_tables: null
    out_transform: null
    summary_table: "                            OLS Regression Results           \
        \                 \n==============================================================================\n\
        Dep. Variable:              res_value   R-squared:                       0.776\n\
        Model:                            OLS   Adj. R-squared:                  0.776\n\
        Method:                 Least Squares   F-statistic:                 1.018e+04\n\
        Date:                Tue, 29 Sep 2026   Prob (F-statistic):              \
        \ 0.00\nTime:                        22:03:57   Log-Likelihood:          \
        \  -4.7680e+05\nNo. Observations:               35233   AIC:             \
        \            9.536e+05\nDf Residuals:                   35220   BIC:     \
        \                    9.537e+05\nDf Model:                          12    \
        \                                     \nCovariance Type:            nonrobust\
        \                                         \n=============================================================================================================\n\
        \                                                coef    std err         \
        \ t      P>|t|      [0.025      0.975]\n-------------------------------------------------------------------------------------------------------------\n\
        Intercept                                  8.036e+05   1088.305    738.404\
        \      0.000    8.01e+05    8.06e+05\nst_ln_res_value_ave_800_flat       \
        \        3.195e+05   2943.819    108.546      0.000    3.14e+05    3.25e+05\n\
        st_block_groups_median_income              6.515e+04   1551.899     41.978\
        \      0.000    6.21e+04    6.82e+04\nst_block_groups_median_year_built  \
        \       -1.523e+04   1078.041    -14.130      0.000   -1.73e+04   -1.31e+04\n\
        st_block_groups_prop_worker_aggr_sector_2 -2.171e+04   1163.192    -18.660\
        \      0.000    -2.4e+04   -1.94e+04\nst_block_groups_prop_worker_aggr_sector_5\
        \  -2.03e+04   1342.082    -15.124      0.000   -2.29e+04   -1.77e+04\nst_sum_middle_ave_3200_flat\
        \                2.135e+04   1470.439     14.520      0.000    1.85e+04  \
        \  2.42e+04\nst_sum_sf_ave_3200_flat                   -3.069e+04   1915.873\
        \    -16.019      0.000   -3.44e+04   -2.69e+04\nst_ln_res_value_ave_3200_flat\
        \             -3.536e+04   3302.969    -10.705      0.000   -4.18e+04   -2.89e+04\n\
        st_prop_aggr_sector_id_4_ave_3200_flat     1.912e+04   2036.317      9.390\
        \      0.000    1.51e+04    2.31e+04\nst_block_groups_prop_worker_aggr_sector_3\
        \ -1.079e+04   1481.115     -7.282      0.000   -1.37e+04   -7882.419\nst_is_urban_center_sum_3200_flat\
        \           8703.7064   1180.518      7.373      0.000    6389.854     1.1e+04\n\
        st_block_groups_prop_worker_aggr_occ_2    -1.479e+04   2330.351     -6.345\
        \      0.000   -1.94e+04   -1.02e+04\n==============================================================================\n\
        Omnibus:                    27581.436   Durbin-Watson:                   1.588\n\
        Prob(Omnibus):                  0.000   Jarque-Bera (JB):          4218984.632\n\
        Skew:                           2.971   Prob(JB):                        \
        \ 0.00\nKurtosis:                      56.278   Cond. No.                \
        \         8.50\n==============================================================================\n\
        \nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors\
        \ is correctly specified."
    tables: blocks
    tags: []
    template: OLSRegressionStep
    template_version: '0.3'
