modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_housing_units
    alt_filters: null
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters: (recent_mover == 1) & (income_quartile == 2)
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - -0.04985589920880061
    - -0.3232399019248557
    - -0.13010203033250714
    - 1.9410396143678323
    - 0.07353764694726198
    - -0.0970829375482414
    - 0.5103303713280691
    max_iter: null
    mct_intx_ops: null
    model_expression: st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_ln_block_groups_mean_res_rent + st_is_transit_stop_sum_1600_flat + st_sum_income_ave_1600_flat
        + st_block_groups_prop_built_after_2010_1 + st_block_groups_prop_children_0
        + st_ln_block_groups_density_housing_units - 1
    name: hlcm3
    out_alt_filters: vacant_housing_units > 0
    out_alternatives: null
    out_chooser_filters: (block_id == -1) & (income_quartile == 2)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:         214,555\nModel:\
        \         Multinomial Logit   Df Residuals:             214,548\nMethod: \
        \      Maximum Likelihood   Df Model:                       7\nDate:     \
        \            2026-09-13   Pseudo R-squ.:              0.067\nTime:       \
        \               09:09   Pseudo R-bar-squ.:          0.067\nAIC:          \
        \     1,842,866.647   Log-Likelihood:      -921,426.324\nBIC:            \
        \   1,842,938.582   LL-Null:             -988,062.289\n=============================================================================================================================\n\
        \                                                                        \
        \     coef   std err          z     P>|z|   Conf. Int.\n-----------------------------------------------------------------------------------------------------------------------------\n\
        st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time  \
        \ -0.0499     0.005    -10.465     0.000             \nst_ln_block_groups_mean_res_rent\
        \                                          -0.3232     0.003   -107.288  \
        \   0.000             \nst_is_transit_stop_sum_1600_flat                 \
        \                         -0.1301     0.002    -54.008     0.000         \
        \    \nst_sum_income_ave_1600_flat                                       \
        \         1.9410     0.007    286.749     0.000             \nst_block_groups_prop_built_after_2010_1\
        \                                    0.0735     0.002     33.709     0.000\
        \             \nst_block_groups_prop_children_0                          \
        \                 -0.0971     0.003    -31.374     0.000             \nst_ln_block_groups_density_housing_units\
        \                                   0.5103     0.003    173.734     0.000\
        \             \n============================================================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
