modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_hu_spaces
    alt_filters: null
    alt_sample_size: 50
    alternatives: blocks
    choice_column: block_id
    chooser_filters: (year_built > 2010) & (unit_type_id == 4)
    chooser_sample_size: null
    chooser_size: null
    choosers: housing_units
    constrained_choices: true
    fitted_parameters:
    - -0.1980626855672153
    - -0.465203588428131
    - 0.12905820910138824
    - -0.8151044174064987
    - 0.060186570931621115
    - 0.03417036757158954
    - -0.1499653379868478
    - 0.282488528279768
    - 0.0925089564532824
    - 1.0121960497346953
    - 0.02677655189793071
    - 0.04335272836429415
    - 0.03641395292189078
    - -0.15906446190846796
    - 0.5981976073369738
    - -0.3881021216167029
    max_iter: null
    mct_intx_ops: null
    model_expression: major_road_node_sum_800_flat + st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_prop_aggr_sector_id_1_ave_1600_flat + st_prop_aggr_sector_id_2_ave_1600_flat
        + st_prop_aggr_sector_id_3_ave_1600_flat + st_prop_aggr_sector_id_4_ave_1600_flat
        + st_prop_aggr_sector_id_5_ave_1600_flat + st_ln_block_groups_mean_res_value
        + st_ln_block_groups_mean_res_rent + st_total_households_sum_2000_linear +
        st_block_groups_median_year_built + st_is_transit_stop_sum_1600_flat + st_block_groups_median_income
        + st_block_groups_prop_built_after_2010_1 + st_prop_children_0_ave_400_flat
        + st_sum_income_ave_1600_flat - 1
    name: hulcm4_calib
    out_alt_filters: vacant_hu_spaces > 0
    out_alternatives: null
    out_chooser_filters: (block_id == -1) & (year_built > 2010) & (unit_type_id ==
        4)
    out_choosers: null
    out_column: null
    summary_table: null
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
