modelmanager_version: 0.3.dev0

saved_object:
    alt_capacity: vacant_hu_spaces
    alt_filters: null
    alt_sample_size: 50
    alternatives: blocks
    choice_column: block_id
    chooser_filters: (year_built > 2010) & (unit_type_id == 4)
    chooser_sample_size: null
    chooser_size: null
    choosers: housing_units
    constrained_choices: true
    fitted_parameters:
    - 0.06770916818308267
    - 0.3161384713515356
    - 0.016920799642834144
    - 0.057068700163232296
    - 0.23032551489749833
    - -0.06317966130458492
    - 0.15552125037558892
    - 0.06949054979933873
    - 0.1302154014409154
    - -0.06291343804235969
    - -0.020447568629063315
    - 0.05700039051644885
    - -0.7590807743194748
    - 0.49972449791834633
    - 0.5107404968280076
    - 2.04816175088462
    max_iter: null
    mct_intx_ops: null
    model_expression: major_road_node_sum_800_flat + st_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time
        + st_prop_aggr_sector_id_1_ave_1600_flat + st_prop_aggr_sector_id_2_ave_1600_flat
        + st_prop_aggr_sector_id_3_ave_1600_flat + st_prop_aggr_sector_id_4_ave_1600_flat
        + st_prop_aggr_sector_id_5_ave_1600_flat + st_ln_block_groups_mean_res_value
        + st_ln_block_groups_mean_res_rent + st_total_households_sum_2000_linear +
        st_block_groups_median_year_built + st_is_transit_stop_sum_1600_flat + st_block_groups_median_income
        + st_block_groups_prop_built_after_2010_1 + st_prop_children_0_ave_400_flat
        + st_sum_income_ave_1600_flat - 1
    name: hulcm4
    out_alt_filters: vacant_hu_spaces > 0
    out_alternatives: null
    out_chooser_filters: (block_id == -1) & (year_built > 2010) & (unit_type_id ==
        4)
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         15,441\nModel:\
        \         Multinomial Logit   Df Residuals:             15,425\nMethod:  \
        \     Maximum Likelihood   Df Model:                     16\nDate:       \
        \          2026-09-13   Pseudo R-squ.:             0.246\nTime:          \
        \            09:18   Pseudo R-bar-squ.:         0.246\nAIC:              \
        \    91,110.668   Log-Likelihood:      -45,539.334\nBIC:                 \
        \ 91,232.985   LL-Null:             -60,405.547\n============================================================================================================================\n\
        \                                                                        \
        \     coef   std err         z     P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------------------------------------\n\
        major_road_node_sum_800_flat                                             \
        \  0.0677     0.010     7.034     0.000             \nst_ln_zones_total_jobs_15_minutes_am_single_vehicle_to_work_travel_time\
        \    0.3161     0.025    12.659     0.000             \nst_prop_aggr_sector_id_1_ave_1600_flat\
        \                                     0.0169     0.013     1.319     0.187\
        \             \nst_prop_aggr_sector_id_2_ave_1600_flat                   \
        \                  0.0571     0.012     4.910     0.000             \nst_prop_aggr_sector_id_3_ave_1600_flat\
        \                                     0.2303     0.010    23.164     0.000\
        \             \nst_prop_aggr_sector_id_4_ave_1600_flat                   \
        \                 -0.0632     0.015    -4.179     0.000             \nst_prop_aggr_sector_id_5_ave_1600_flat\
        \                                     0.1555     0.009    17.327     0.000\
        \             \nst_ln_block_groups_mean_res_value                        \
        \                  0.0695     0.012     5.899     0.000             \nst_ln_block_groups_mean_res_rent\
        \                                           0.1302     0.016     8.164   \
        \  0.000             \nst_total_households_sum_2000_linear               \
        \                        -0.0629     0.031    -2.061     0.039           \
        \  \nst_block_groups_median_year_built                                   \
        \      -0.0204     0.013    -1.565     0.118             \nst_is_transit_stop_sum_1600_flat\
        \                                           0.0570     0.009     6.478   \
        \  0.000             \nst_block_groups_median_income                     \
        \                        -0.7591     0.015   -49.437     0.000           \
        \  \nst_block_groups_prop_built_after_2010_1                             \
        \       0.4997     0.010    49.148     0.000             \nst_prop_children_0_ave_400_flat\
        \                                            0.5107     0.015    34.990  \
        \   0.000             \nst_sum_income_ave_1600_flat                      \
        \                          2.0482     0.046    44.507     0.000          \
        \   \n============================================================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.3.dev0
